version: "3.7"
services:
  # From https://github.com/Zenika/alpine-chrome
  chromium:
    image: zenika/alpine-chrome:latest
    command: [
    "/usr/bin/google-chrome", \
    "--headless", \
    "--no-sandbox", \
    "--disable-gpu", \
    "--remote-debugging-address=0.0.0.0", \
    "--remote-debugging-port=9222", \
    "--use-mock-keychain", \
    "--password-store=basic", \
    "--disable-dev-shm-usage", \
    "--test-type=webdriver", \
    "--enable-automation", \
    "--disable-hang-monitor", \
    "--disable-background-networking", \
    "--disable-default-apps", \
    "--disable-extensions", \
    "--disable-sync", \
    "--disable-web-resources", \
    "--disable-notifications", \
    "--disable-translate", \
    "--hide-scrollbars", \
    "--metrics-recording-only", \
    "--mute-audio", \
    "--no-first-run", \
    "--safebrowsing-disable-auto-update", \
    ]
    security_opt:
      - seccomp:chrome.json
    cap_add:
      - SYS_ADMIN

  api:
    build:
      context: screenshooter
    ports:
      - "1234:8001"
